using System.Reflection;
using System.Text;
using System.Text.Json;

namespace PKHeX.Everywhere.Engine.CodeGen;

/// <summary>
/// The type rules here must match the JSON that PKHeX.Everywhere.Engine.Generators emits.
/// </summary>
public static class TypeScript
{
    private const string Header = "// Generated by PKHeX.Everywhere.Engine.CodeGen. Do not edit.\n";

    /// <summary>
    /// Writes files relative to the SDK's <c>packages</c> directory.
    /// </summary>
    public static IEnumerable<(string File, string Content)> Write(Contract contract)
    {
        var docs = new Docs();
        var types = new TypeCollector(BinaryOutputs(contract), docs);
        var client = Client(contract, types, docs);
        foreach (var engineEvent in contract.Events) types.Render(engineEvent, null);

        yield return ("engine/src/generated/types.ts", types.Declarations() + Events(contract));
        yield return ("engine/src/generated/client.ts", client);
        yield return ("engine/src/generated/errors.ts", Errors(contract));
        yield return ("engine/src/generated/topics.ts", Topics(contract));
        yield return ("react/src/generated/hooks.ts", Hooks(contract));
    }

    // A returned record's bytes become a Uint8Array only when the client can convert them, so the record must never reach JS any other way.
    // That covers the records it holds bytes through, such as each save a transfer returns. A record a call takes keeps its bytes as Base64,
    // and so do the records it holds, unless a call also returns them inside another record: then the client encodes them back on the way in.
    private static BinaryRecords BinaryOutputs(Contract contract)
    {
        var inputs = contract.Calls.SelectMany(c => c.Parameters).Select(p => Nullable.GetUnderlyingType(p.Type) ?? p.Type).ToHashSet();
        var outputs = contract.Calls
            .Select(c => Nullable.GetUnderlyingType(c.ReturnType) ?? c.ReturnType)
            .Where(t => Contract.IsObject(t) && BytesPaths(t, inputs).Any() && !inputs.Contains(t))
            .SelectMany(t => BytesHolders(t, inputs).Prepend(t))
            .ToHashSet();
        return new BinaryRecords(outputs, inputs);
    }

    private sealed record BinaryRecords(HashSet<Type> Outputs, HashSet<Type> Inputs)
    {
        public IEnumerable<string> OutputPaths(Type type) => BytesPaths(type, Inputs);

        public IEnumerable<string> InputPaths(Type type) => Objects(type).SelectMany(p => Outputs.Contains(p.Type)
            ? OutputPaths(p.Type).Select(path => $"{p.Name}.{path}")
            : InputPaths(p.Type).Select(path => $"{p.Name}.{path}"));
    }

    // An array is crossed as if it were its element: the client converts each one.
    private static IEnumerable<(string Name, Type Type)> Objects(Type type) => TypeCollector.Properties(type)
        .Select(p => (Name: JsonNamingPolicy.CamelCase.ConvertName(p.Name), Type: TypeCollector.ElementType(p.PropertyType, null)?.Element ?? p.PropertyType))
        .Where(p => Contract.IsObject(p.Type));

    private static IEnumerable<string> BytesPaths(Type type, HashSet<Type> inputs) => TypeCollector.Properties(type)
        .Where(p => p.PropertyType == typeof(byte[]))
        .Select(p => JsonNamingPolicy.CamelCase.ConvertName(p.Name))
        .Concat(Objects(type).Where(p => !inputs.Contains(p.Type)).SelectMany(p => BytesPaths(p.Type, inputs).Select(path => $"{p.Name}.{path}")));

    private static IEnumerable<Type> BytesHolders(Type type, HashSet<Type> inputs) => Objects(type)
        .Select(p => p.Type)
        .Where(t => !inputs.Contains(t) && BytesPaths(t, inputs).Any())
        .SelectMany(t => BytesHolders(t, inputs).Prepend(t));

    private static string? Requirements(Call call, bool react)
    {
        var needs = new List<string>();
        var codes = new List<string>();
        if (call.RequiresSave)
        {
            needs.Add("a loaded save");
            codes.Add("`no-save`");
        }

        if (call.RequiresDraft)
        {
            needs.Add("an open draft");
            codes.Add("`no-draft`");
        }

        if (needs.Count == 0) return null;

        var wrap = react && call.RequiresSave ? " Wrap in `<RequireGame>`." : "";
        return $"Requires {string.Join(" and ", needs)}; throws {string.Join(" or ", codes)} otherwise.{wrap}";
    }

    private static string? Doc(Call call, IEnumerable<Parameter> parameters, Docs docs, bool react, string indent)
    {
        var summary = string.Join(" ", new[] { docs.Summary(call.Method), Requirements(call, react) }.OfType<string>());
        var tags = parameters
            .Select(p => docs.Param(call.Method, p.Name) is { } text ? $"@param {p.Name} {text}" : null)
            .OfType<string>()
            .ToList();

        if (tags.Count == 0) return summary == "" ? null : $"{indent}/** {summary} */";

        var lines = (summary == "" ? tags : [summary, "", .. tags]).Select(line => line == "" ? $"{indent} *" : $"{indent} * {line}");
        return $"{indent}/**\n{string.Join("\n", lines)}\n{indent} */";
    }

    private static string Parameters(IEnumerable<Parameter> parameters, TypeCollector types) =>
        string.Join(", ", parameters.Select(p => $"{p.Name}{(p.IsOptional ? "?" : "")}: {types.Render(p.Type, p.Nullability, Direction.Input)}"));

    private static string Topics(Contract contract) => $$"""
        {{Header}}
        import type { QueryName } from './client'

        export const topics = [{{string.Join(", ", contract.Topics.Select(Quote))}}] as const

        export type Topic = (typeof topics)[number] | `${(typeof topics)[number]}/${string}`

        export const queryTopics: Record<QueryName, readonly Topic[]> = {
        {{string.Concat(contract.Queries.Select(c => $"  {Quote(c.Name)}: [{string.Join(", ", c.Topics.Select(Quote))}],\n"))}}}

        """;

    private static string Events(Contract contract) =>
        $"\n/** Every event `engine.onEvent` delivers. Narrow on `type`. */\nexport type EngineEvent = {(contract.Events.Count == 0 ? "never" : string.Join(" | ", contract.Events.Select(e => e.Name)))}\n";

    private static string Errors(Contract contract) => $"""
        {Header}
        export const errorCodes = [{string.Join(", ", contract.ErrorCodes.Select(Quote))}] as const

        export type ErrorCode = (typeof errorCodes)[number]

        """;

    private static string Client(Contract contract, TypeCollector types, Docs docs)
    {
        var root = new Node();
        foreach (var call in contract.Calls)
        {
            var node = call.Name.Split('.').SkipLast(1).Aggregate(root, (n, segment) => n.Child(segment));
            node.Calls.Add((call.Name.Split('.').Last(), call));
        }

        var signatures = new StringBuilder();
        var implementations = new StringBuilder();
        WriteNode(root, types, docs, signatures, implementations, 1);

        var imports = types.Names.Count == 0
            ? ""
            : $"import type {{ {string.Join(", ", types.Names.Order(StringComparer.Ordinal))} }} from './types'\n";
        if (types.Helpers.Count > 0)
            imports = $"import {{ {string.Join(", ", types.Helpers.Order(StringComparer.Ordinal))} }} from '../binary'\n" + imports;
        if (imports != "") imports += "\n";

        return $$"""
            {{Header}}
            {{imports}}export type Invoke = <T>(call: CallName, args: unknown[]) => Promise<T>

            export const queries = [{{Names(contract.Calls, CallKind.Query)}}] as const

            export const commands = [{{Names(contract.Calls, CallKind.Command)}}] as const

            export type QueryName = (typeof queries)[number]

            export type CommandName = (typeof commands)[number]

            export type CallName = QueryName | CommandName

            export interface EngineClient {
            {{signatures}}}

            export function createClient(invoke: Invoke): EngineClient {
              return {
            {{implementations}}  }
            }

            """;
    }

    private static string Names(IEnumerable<Call> calls, CallKind kind) =>
        string.Join(", ", calls.Where(c => c.Kind == kind).Select(c => Quote(c.Name)));

    private static string Hooks(Contract contract)
    {
        var docs = new Docs();
        var types = new TypeCollector(BinaryOutputs(contract), docs);
        var hooks = new List<string>();
        var usesCommands = false;

        foreach (var entity in contract.Calls.GroupBy(c => c.Entity))
        {
            var get = entity.FirstOrDefault(c => c is { Kind: CallKind.Query, Verb: "get" });
            if (get is null) continue;

            Parameter? handle;
            if (get.Parameters is []) handle = null;
            else if (get.Parameters is [{ IsHandle: true } single]) handle = single;
            else continue;

            var name = entity.Select(c => c.Hook).FirstOrDefault(h => h is not null) ?? $"use{char.ToUpperInvariant(entity.Key[0])}{entity.Key[1..]}";
            var commands = entity.Where(c => c.Kind == CallKind.Command).ToList();
            usesCommands |= commands.Count > 0;

            var hook = new StringBuilder();
            var parameter = handle is null ? "" : $"{handle.Name}: {types.Render(handle.Type, handle.Nullability)}";
            if (Requirements(get, react: true) is { } doc) hook.AppendLine($"/** {doc} */");
            hook.AppendLine($"export function {name}({parameter}) {{");
            if (commands.Count > 0) hook.AppendLine("  const engine = useEngine()");
            hook.AppendLine($"  const {entity.Key} = useQuery({Quote(get.Name)}{(handle is null ? "" : $", {handle.Name}")})");

            if (commands.Count == 0)
            {
                hook.AppendLine($"  return {{ {entity.Key} }}");
                hook.AppendLine("}");
                hooks.Add(hook.ToString());
                continue;
            }

            if (handle is not null) hook.AppendLine($"  const key = JSON.stringify({handle.Name})");
            hook.AppendLine("  const commands = useMemo(");
            hook.AppendLine("    () => ({");
            foreach (var command in commands)
            {
                var bound = handle is not null && command.Parameters.FirstOrDefault() is { IsHandle: true } first && first.Type == handle.Type;
                var own = command.Parameters.Skip(bound ? 1 : 0).ToList();
                var parameters = Parameters(own, types);
                var arguments = string.Join(", ", (bound ? [handle!.Name] : Array.Empty<string>()).Concat(own.Select(p => p.Name)));
                if (Doc(command, own, docs, react: true, "      ") is { } commandDoc) hook.AppendLine(commandDoc);
                hook.AppendLine($"      {command.Verb}: ({parameters}) => engine.{command.Name}({arguments}),");
            }

            hook.AppendLine("    }),");
            hook.AppendLine(handle is null ? "    [engine]," : "    [engine, key],");
            hook.AppendLine("  )");
            hook.AppendLine($"  return {{ {entity.Key}, ...commands }}");
            hook.AppendLine("}");
            hooks.Add(hook.ToString());
        }

        var imports = new StringBuilder();
        if (usesCommands) imports.AppendLine("import { useMemo } from 'react'");
        if (types.Names.Count > 0)
            imports.AppendLine($"import type {{ {string.Join(", ", types.Names.Order(StringComparer.Ordinal))} }} from '@pkhex-everywhere/engine'");
        if (usesCommands) imports.AppendLine("import { useEngine } from '../EngineProvider'");
        imports.AppendLine("import { useQuery } from '../useQuery'");

        return $"{Header}\n{imports}\n{string.Join("\n", hooks)}";
    }

    private static void WriteNode(Node node, TypeCollector types, Docs docs, StringBuilder signatures, StringBuilder implementations, int depth)
    {
        var indent = new string(' ', depth * 2);
        foreach (var (name, child) in node.Children)
        {
            signatures.AppendLine($"{indent}{name}: {{");
            implementations.AppendLine($"{indent}  {name}: {{");
            WriteNode(child, types, docs, signatures, implementations, depth + 1);
            signatures.AppendLine($"{indent}}}");
            implementations.AppendLine($"{indent}  }},");
        }

        foreach (var (name, call) in node.Calls)
        {
            var parameters = Parameters(call.Parameters, types);
            var arguments = string.Join(", ", call.Parameters.Select(p => p.Name));
            var result = call.ReturnType == typeof(void) ? "void" : types.Render(call.ReturnType, call.ReturnNullability, Direction.Output);

            if (Doc(call, call.Parameters, docs, react: false, indent) is { } doc) signatures.AppendLine(doc);
            signatures.AppendLine($"{indent}{name}({parameters}): Promise<{result}>");
            implementations.AppendLine($"{indent}  {name}: {Implementation(call, result, types)},");
        }
    }

    private static string Implementation(Call call, string result, TypeCollector types)
    {
        var arguments = call.Parameters.Select((p, i) => Argument(call, i, types)).ToList();
        var invoke = $"invoke({Quote(call.Name)}, [{string.Join(", ", arguments)}])";
        var bytes = types.IsBinaryOutput(call.ReturnType) ? types.Records.OutputPaths(call.ReturnType).ToList() : [];
        if (bytes.Count > 0)
        {
            types.Helpers.Add("withBytes");
            invoke = $"withBytes(await invoke<{result}>({Quote(call.Name)}, [{string.Join(", ", arguments)}]), [{string.Join(", ", bytes.Select(Quote))}])";
        }

        var async = bytes.Count > 0 || arguments.Any(a => a.Contains("await "));
        return $"{(async ? "async " : "")}({string.Join(", ", call.Parameters.Select(p => p.Name))}) => {invoke}";
    }

    private static string Argument(Call call, int index, TypeCollector types)
    {
        var parameter = call.Parameters[index];
        if (parameter.Type == typeof(byte[]))
        {
            types.Helpers.Add("toBase64");
            return parameter.Nullability.ReadState == NullabilityState.Nullable
                ? $"{parameter.Name} == null ? null : await toBase64({parameter.Name})"
                : $"await toBase64({parameter.Name})";
        }

        if (parameter is { Name: "fileName" } && parameter.Type == typeof(string) && index > 0 && call.Parameters[index - 1].Type == typeof(byte[]))
        {
            types.Helpers.Add("fileNameOf");
            return $"{parameter.Name} ?? fileNameOf({call.Parameters[index - 1].Name})";
        }

        var type = Nullable.GetUnderlyingType(parameter.Type) ?? parameter.Type;
        if (Contract.IsObject(type) && types.Records.InputPaths(type).ToList() is { Count: > 0 } paths)
        {
            types.Helpers.Add("withBase64");
            return $"await withBase64({parameter.Name}, [{string.Join(", ", paths.Select(Quote))}])";
        }

        return parameter.Name;
    }

    private static string Quote(string value) => $"'{value}'";

    private sealed class Node
    {
        public List<(string Name, Node Node)> Children { get; } = [];
        public List<(string Name, Call Call)> Calls { get; } = [];

        public Node Child(string name)
        {
            var existing = Children.FirstOrDefault(c => c.Name == name).Node;
            if (existing is not null) return existing;

            var child = new Node();
            Children.Add((name, child));
            return child;
        }
    }

    private enum Direction
    {
        Nested,
        NestedInput,
        Input,
        Output,
    }

    private sealed class TypeCollector(BinaryRecords binary, Docs docs)
    {
        private const string Binary = "Binary";
        private const string Base64 = "Base64";

        private readonly NullabilityInfoContext _nullability = new();
        private readonly Dictionary<string, Type> _types = new();

        public ICollection<string> Names => _types.Keys;

        public HashSet<string> Helpers { get; } = [];

        public BinaryRecords Records => binary;

        public bool IsBinaryOutput(Type type) => binary.Outputs.Contains(type);

        public string Render(Type type, NullabilityInfo? info, Direction direction = Direction.Nested)
        {
            if (Nullable.GetUnderlyingType(type) is { } underlying)
                return $"{Render(underlying, null, direction)} | null";

            if (!type.IsValueType && info?.ReadState == NullabilityState.Nullable)
                return $"{Render(type, null, direction)} | null";

            if (type.IsEnum) return Register(type);

            if (type == typeof(byte[]))
            {
                switch (direction)
                {
                    case Direction.Input:
                        _types[Binary] = type;
                        return Binary;
                    case Direction.Output:
                        throw new NotSupportedException("A call can't return bytes on their own. Return a record with a byte[] property instead.");
                    default:
                        _types[Base64] = type;
                        return Base64;
                }
            }

            switch (Type.GetTypeCode(type))
            {
                case TypeCode.String:
                    return "string";
                case TypeCode.Boolean:
                    return "boolean";
                case TypeCode.Byte or TypeCode.SByte or TypeCode.Int16 or TypeCode.UInt16 or TypeCode.Int32 or TypeCode.UInt32
                    or TypeCode.Int64 or TypeCode.UInt64 or TypeCode.Single or TypeCode.Double or TypeCode.Decimal:
                    return "number";
            }

            if (ElementType(type, info) is var (element, elementInfo))
            {
                var rendered = Render(element, elementInfo, direction);
                return rendered.Contains('|') ? $"({rendered})[]" : $"{rendered}[]";
            }

            if (IsBinaryOutput(type) && direction == Direction.Nested)
                throw new InvalidOperationException($"{type.Name} carries bytes and is returned by a call, so it can only reach JS as that call's result or in a call's input.");

            if (Contract.IsBranded(type) || Contract.IsObject(type)) return Register(type);

            throw new NotSupportedException($"Type {type.FullName} can't cross the engine boundary.");
        }

        private string Register(Type type)
        {
            if (_types.TryGetValue(type.Name, out var known) && known != type)
                throw new InvalidOperationException($"Two engine types are named {type.Name}: {known.FullName} and {type.FullName}.");

            _types[type.Name] = type;
            return type.Name;
        }

        public string Declarations()
        {
            var declarations = new SortedDictionary<string, string>(StringComparer.Ordinal);
            while (_types.Keys.FirstOrDefault(n => !declarations.ContainsKey(n)) is { } name)
                declarations[name] = Declare(name, _types[name]);

            return Header + string.Concat(declarations.Values.Select(d => "\n" + d));
        }

        private string Declare(string name, Type type)
        {
            if (name == Binary) return "/** Bytes a call accepts. A `File` is a `Blob`, so it works too. */\nexport type Binary = Uint8Array | ArrayBuffer | Blob\n";
            if (name == Base64) return "/** Bytes encoded as a base64 string. */\nexport type Base64 = string\n";

            var doc = docs.Comment(type);
            if (type.IsEnum)
            {
                var members = Enum.GetNames(type).Select(n => Quote(JsonNamingPolicy.CamelCase.ConvertName(n)));
                return $"{doc}export type {type.Name} = {string.Join(" | ", members)}\n";
            }

            if (Contract.IsBranded(type))
                return $"{doc}export type {type.Name} = string & {{ readonly __brand: {Quote(type.Name)} }}\n";

            var optional = OptionalParameters(type);
            var sb = new StringBuilder($"{doc}export interface {type.Name} {{\n");
            if (Contract.IsEvent(type)) sb.AppendLine($"  type: {Quote(JsonNamingPolicy.CamelCase.ConvertName(type.Name))}");
            foreach (var property in Properties(type))
            {
                var rendered = IsBinaryOutput(type) && property.PropertyType == typeof(byte[])
                    ? "Uint8Array<ArrayBuffer>"
                    : Render(property.PropertyType, _nullability.Create(property), PropertyDirection(type));
                var mark = optional.Contains(property.Name) && rendered.EndsWith(" | null") ? "?" : "";
                sb.Append(docs.Comment(property, "  "));
                sb.AppendLine($"  {JsonNamingPolicy.CamelCase.ConvertName(property.Name)}{mark}: {rendered}");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private Direction PropertyDirection(Type type) =>
            IsBinaryOutput(type) ? Direction.Output
            : binary.Inputs.Contains(type) && binary.InputPaths(type).Any() ? Direction.NestedInput
            : Direction.Nested;

        // The JSON reader passes null for a missing property, so a nullable constructor parameter with a default can be left out.
        private static HashSet<string> OptionalParameters(Type type) => type
            .GetConstructors()
            .MaxBy(c => c.GetParameters().Length)
            ?.GetParameters()
            .Where(p => p.HasDefaultValue)
            .Select(p => p.Name!)
            .ToHashSet(StringComparer.OrdinalIgnoreCase) ?? [];

        public static IEnumerable<PropertyInfo> Properties(Type type) => type
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetMethod?.IsPublic == true && p.GetIndexParameters().Length == 0)
            .DistinctBy(p => p.Name);

        public static (Type Element, NullabilityInfo? Info)? ElementType(Type type, NullabilityInfo? info)
        {
            if (type.IsArray) return (type.GetElementType()!, info?.ElementType);
            if (type == typeof(string)) return null;

            var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                ? type
                : type.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));

            if (enumerable is null) return null;

            var elementInfo = info?.GenericTypeArguments.Length == 1 ? info.GenericTypeArguments[0] : null;
            return (enumerable.GetGenericArguments()[0], elementInfo);
        }
    }
}
