using System.Reflection;
using System.Text;
using System.Text.Json;

namespace PKHeX.Everywhere.Engine.CodeGen;

/// <summary>
/// The type rules here must match the JSON that PKHeX.Everywhere.Engine.Generators emits.
/// </summary>
public static class TypeScript
{
    private const string Header = "// Generated by PKHeX.Everywhere.Engine.CodeGen. Do not edit.\n";

    public static IEnumerable<(string File, string Content)> Write(Contract contract)
    {
        var types = new TypeCollector();
        var client = Client(contract, types);

        yield return ("types.ts", types.Declarations());
        yield return ("client.ts", client);
        yield return ("errors.ts", Errors(contract));
        yield return ("topics.ts", Topics(contract));
    }

    private static string Topics(Contract contract) => $$"""
        {{Header}}
        import type { CallName } from './client'

        export const topics = [{{string.Join(", ", contract.Topics.Select(Quote))}}] as const

        export type Topic = (typeof topics)[number] | `${(typeof topics)[number]}/${string}`

        export const queryTopics: Record<CallName, readonly Topic[]> = {
        {{string.Concat(contract.Calls.Select(c => $"  {Quote(c.Name)}: [{string.Join(", ", c.Topics.Select(Quote))}],\n"))}}}

        """;

    private static string Errors(Contract contract) => $"""
        {Header}
        export const errorCodes = [{string.Join(", ", contract.ErrorCodes.Select(Quote))}] as const

        export type ErrorCode = (typeof errorCodes)[number]

        """;

    private static string Client(Contract contract, TypeCollector types)
    {
        var root = new Node();
        foreach (var call in contract.Calls)
        {
            var node = call.Name.Split('.').SkipLast(1).Aggregate(root, (n, segment) => n.Child(segment));
            node.Calls.Add((call.Name.Split('.').Last(), call));
        }

        var signatures = new StringBuilder();
        var implementations = new StringBuilder();
        WriteNode(root, types, signatures, implementations, 1);

        var imports = types.Names.Count == 0
            ? ""
            : $"import type {{ {string.Join(", ", types.Names.Order(StringComparer.Ordinal))} }} from './types'\n\n";

        return $$"""
            {{Header}}
            {{imports}}export type Invoke = <T>(call: CallName, args: unknown[]) => Promise<T>

            export const calls = [{{string.Join(", ", contract.Calls.Select(c => Quote(c.Name)))}}] as const

            export type CallName = (typeof calls)[number]

            export interface EngineClient {
            {{signatures}}}

            export function createClient(invoke: Invoke): EngineClient {
              return {
            {{implementations}}  }
            }

            """;
    }

    private static void WriteNode(Node node, TypeCollector types, StringBuilder signatures, StringBuilder implementations, int depth)
    {
        var indent = new string(' ', depth * 2);
        foreach (var (name, child) in node.Children)
        {
            signatures.AppendLine($"{indent}{name}: {{");
            implementations.AppendLine($"{indent}  {name}: {{");
            WriteNode(child, types, signatures, implementations, depth + 1);
            signatures.AppendLine($"{indent}}}");
            implementations.AppendLine($"{indent}  }},");
        }

        foreach (var (name, call) in node.Calls)
        {
            var parameters = string.Join(", ", call.Parameters.Select(p => $"{p.Name}: {types.Render(p.Type, p.Nullability)}"));
            var arguments = string.Join(", ", call.Parameters.Select(p => p.Name));
            var result = call.ReturnType == typeof(void) ? "void" : types.Render(call.ReturnType, call.ReturnNullability);

            signatures.AppendLine($"{indent}{name}({parameters}): Promise<{result}>");
            implementations.AppendLine($"{indent}  {name}: ({arguments}) => invoke({Quote(call.Name)}, [{arguments}]),");
        }
    }

    private static string Quote(string value) => $"'{value}'";

    private sealed class Node
    {
        public List<(string Name, Node Node)> Children { get; } = [];
        public List<(string Name, Call Call)> Calls { get; } = [];

        public Node Child(string name)
        {
            var existing = Children.FirstOrDefault(c => c.Name == name).Node;
            if (existing is not null) return existing;

            var child = new Node();
            Children.Add((name, child));
            return child;
        }
    }

    private sealed class TypeCollector
    {
        private readonly NullabilityInfoContext _nullability = new();
        private readonly Dictionary<string, Type> _types = new();

        public ICollection<string> Names => _types.Keys;

        public string Render(Type type, NullabilityInfo? info)
        {
            if (Nullable.GetUnderlyingType(type) is { } underlying)
                return $"{Render(underlying, null)} | null";

            if (!type.IsValueType && info?.ReadState == NullabilityState.Nullable)
                return $"{Render(type, null)} | null";

            if (type.IsEnum) return Register(type);

            switch (Type.GetTypeCode(type))
            {
                case TypeCode.String:
                    return "string";
                case TypeCode.Boolean:
                    return "boolean";
                case TypeCode.Byte or TypeCode.SByte or TypeCode.Int16 or TypeCode.UInt16 or TypeCode.Int32 or TypeCode.UInt32
                    or TypeCode.Int64 or TypeCode.UInt64 or TypeCode.Single or TypeCode.Double or TypeCode.Decimal:
                    return "number";
            }

            if (ElementType(type, info) is var (element, elementInfo))
            {
                var rendered = Render(element, elementInfo);
                return rendered.Contains('|') ? $"({rendered})[]" : $"{rendered}[]";
            }

            if (Contract.IsBranded(type) || Contract.IsObject(type)) return Register(type);

            throw new NotSupportedException($"Type {type.FullName} can't cross the engine boundary.");
        }

        private string Register(Type type)
        {
            if (_types.TryGetValue(type.Name, out var known) && known != type)
                throw new InvalidOperationException($"Two engine types are named {type.Name}: {known.FullName} and {type.FullName}.");

            _types[type.Name] = type;
            return type.Name;
        }

        public string Declarations()
        {
            var declarations = new SortedDictionary<string, string>(StringComparer.Ordinal);
            while (_types.Keys.FirstOrDefault(n => !declarations.ContainsKey(n)) is { } name)
                declarations[name] = Declare(_types[name]);

            return Header + string.Concat(declarations.Values.Select(d => "\n" + d));
        }

        private string Declare(Type type)
        {
            if (type.IsEnum)
            {
                var members = Enum.GetNames(type).Select(n => Quote(JsonNamingPolicy.CamelCase.ConvertName(n)));
                return $"export type {type.Name} = {string.Join(" | ", members)}\n";
            }

            if (Contract.IsBranded(type))
                return $"export type {type.Name} = string & {{ readonly __brand: {Quote(type.Name)} }}\n";

            var sb = new StringBuilder($"export interface {type.Name} {{\n");
            foreach (var property in Properties(type))
            {
                var name = JsonNamingPolicy.CamelCase.ConvertName(property.Name);
                sb.AppendLine($"  {name}: {Render(property.PropertyType, _nullability.Create(property))}");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static IEnumerable<PropertyInfo> Properties(Type type) => type
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetMethod?.IsPublic == true && p.GetIndexParameters().Length == 0)
            .DistinctBy(p => p.Name);

        private static (Type, NullabilityInfo?)? ElementType(Type type, NullabilityInfo? info)
        {
            if (type.IsArray) return (type.GetElementType()!, info?.ElementType);
            if (type == typeof(string)) return null;

            var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                ? type
                : type.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));

            if (enumerable is null) return null;

            var elementInfo = info?.GenericTypeArguments.Length == 1 ? info.GenericTypeArguments[0] : null;
            return (enumerable.GetGenericArguments()[0], elementInfo);
        }
    }
}
