using System.Reflection;
using System.Text;
using System.Text.Json;

namespace PKHeX.Everywhere.Engine.CodeGen;

/// <summary>
/// The type rules here must match the JSON that PKHeX.Everywhere.Engine.Generators emits.
/// </summary>
public static class TypeScript
{
    private const string Header = "// Generated by PKHeX.Everywhere.Engine.CodeGen. Do not edit.\n";

    /// <summary>
    /// Writes files relative to the SDK's <c>packages</c> directory.
    /// </summary>
    public static IEnumerable<(string File, string Content)> Write(Contract contract)
    {
        var types = new TypeCollector();
        var client = Client(contract, types);
        foreach (var engineEvent in contract.Events) types.Render(engineEvent, null);

        yield return ("engine/src/generated/types.ts", types.Declarations() + Events(contract));
        yield return ("engine/src/generated/client.ts", client);
        yield return ("engine/src/generated/errors.ts", Errors(contract));
        yield return ("engine/src/generated/topics.ts", Topics(contract));
        yield return ("react/src/generated/hooks.ts", Hooks(contract));
    }

    private static string Topics(Contract contract) => $$"""
        {{Header}}
        import type { QueryName } from './client'

        export const topics = [{{string.Join(", ", contract.Topics.Select(Quote))}}] as const

        export type Topic = (typeof topics)[number] | `${(typeof topics)[number]}/${string}`

        export const queryTopics: Record<QueryName, readonly Topic[]> = {
        {{string.Concat(contract.Queries.Select(c => $"  {Quote(c.Name)}: [{string.Join(", ", c.Topics.Select(Quote))}],\n"))}}}

        """;

    private static string Events(Contract contract) =>
        $"\nexport type EngineEvent = {(contract.Events.Count == 0 ? "never" : string.Join(" | ", contract.Events.Select(e => e.Name)))}\n";

    private static string Errors(Contract contract) => $"""
        {Header}
        export const errorCodes = [{string.Join(", ", contract.ErrorCodes.Select(Quote))}] as const

        export type ErrorCode = (typeof errorCodes)[number]

        """;

    private static string Client(Contract contract, TypeCollector types)
    {
        var root = new Node();
        foreach (var call in contract.Calls)
        {
            var node = call.Name.Split('.').SkipLast(1).Aggregate(root, (n, segment) => n.Child(segment));
            node.Calls.Add((call.Name.Split('.').Last(), call));
        }

        var signatures = new StringBuilder();
        var implementations = new StringBuilder();
        WriteNode(root, types, signatures, implementations, 1);

        var imports = types.Names.Count == 0
            ? ""
            : $"import type {{ {string.Join(", ", types.Names.Order(StringComparer.Ordinal))} }} from './types'\n\n";

        return $$"""
            {{Header}}
            {{imports}}export type Invoke = <T>(call: CallName, args: unknown[]) => Promise<T>

            export const queries = [{{Names(contract.Calls, CallKind.Query)}}] as const

            export const commands = [{{Names(contract.Calls, CallKind.Command)}}] as const

            export type QueryName = (typeof queries)[number]

            export type CommandName = (typeof commands)[number]

            export type CallName = QueryName | CommandName

            export interface EngineClient {
            {{signatures}}}

            export function createClient(invoke: Invoke): EngineClient {
              return {
            {{implementations}}  }
            }

            """;
    }

    private static string Names(IEnumerable<Call> calls, CallKind kind) =>
        string.Join(", ", calls.Where(c => c.Kind == kind).Select(c => Quote(c.Name)));

    private static string Hooks(Contract contract)
    {
        var types = new TypeCollector();
        var hooks = new List<string>();
        var usesCommands = false;

        foreach (var entity in contract.Calls.GroupBy(c => c.Entity))
        {
            var get = entity.FirstOrDefault(c => c is { Kind: CallKind.Query, Verb: "get" });
            if (get is null) continue;

            Parameter? handle;
            if (get.Parameters is []) handle = null;
            else if (get.Parameters is [{ IsHandle: true } single]) handle = single;
            else continue;

            var name = entity.Select(c => c.Hook).FirstOrDefault(h => h is not null) ?? $"use{char.ToUpperInvariant(entity.Key[0])}{entity.Key[1..]}";
            var commands = entity.Where(c => c.Kind == CallKind.Command).ToList();
            usesCommands |= commands.Count > 0;

            var hook = new StringBuilder();
            var parameter = handle is null ? "" : $"{handle.Name}: {types.Render(handle.Type, handle.Nullability)}";
            hook.AppendLine($"export function {name}({parameter}) {{");
            if (commands.Count > 0) hook.AppendLine("  const engine = useEngine()");
            hook.AppendLine($"  const {entity.Key} = useQuery({Quote(get.Name)}{(handle is null ? "" : $", {handle.Name}")})");

            if (commands.Count == 0)
            {
                hook.AppendLine($"  return {{ {entity.Key} }}");
                hook.AppendLine("}");
                hooks.Add(hook.ToString());
                continue;
            }

            if (handle is not null) hook.AppendLine($"  const key = JSON.stringify({handle.Name})");
            hook.AppendLine("  const commands = useMemo(");
            hook.AppendLine("    () => ({");
            foreach (var command in commands)
            {
                var bound = handle is not null && command.Parameters.FirstOrDefault() is { IsHandle: true } first && first.Type == handle.Type;
                var own = command.Parameters.Skip(bound ? 1 : 0).ToList();
                var parameters = string.Join(", ", own.Select(p => $"{p.Name}: {types.Render(p.Type, p.Nullability)}"));
                var arguments = string.Join(", ", (bound ? [handle!.Name] : Array.Empty<string>()).Concat(own.Select(p => p.Name)));
                hook.AppendLine($"      {command.Verb}: ({parameters}) => engine.{command.Name}({arguments}),");
            }

            hook.AppendLine("    }),");
            hook.AppendLine(handle is null ? "    [engine]," : "    [engine, key],");
            hook.AppendLine("  )");
            hook.AppendLine($"  return {{ {entity.Key}, ...commands }}");
            hook.AppendLine("}");
            hooks.Add(hook.ToString());
        }

        var imports = new StringBuilder();
        if (usesCommands) imports.AppendLine("import { useMemo } from 'react'");
        if (types.Names.Count > 0)
            imports.AppendLine($"import type {{ {string.Join(", ", types.Names.Order(StringComparer.Ordinal))} }} from '@pkhex-everywhere/engine'");
        if (usesCommands) imports.AppendLine("import { useEngine } from '../EngineProvider'");
        imports.AppendLine("import { useQuery } from '../useQuery'");

        return $"{Header}\n{imports}\n{string.Join("\n", hooks)}";
    }

    private static void WriteNode(Node node, TypeCollector types, StringBuilder signatures, StringBuilder implementations, int depth)
    {
        var indent = new string(' ', depth * 2);
        foreach (var (name, child) in node.Children)
        {
            signatures.AppendLine($"{indent}{name}: {{");
            implementations.AppendLine($"{indent}  {name}: {{");
            WriteNode(child, types, signatures, implementations, depth + 1);
            signatures.AppendLine($"{indent}}}");
            implementations.AppendLine($"{indent}  }},");
        }

        foreach (var (name, call) in node.Calls)
        {
            var parameters = string.Join(", ", call.Parameters.Select(p => $"{p.Name}: {types.Render(p.Type, p.Nullability)}"));
            var arguments = string.Join(", ", call.Parameters.Select(p => p.Name));
            var result = call.ReturnType == typeof(void) ? "void" : types.Render(call.ReturnType, call.ReturnNullability);

            signatures.AppendLine($"{indent}{name}({parameters}): Promise<{result}>");
            implementations.AppendLine($"{indent}  {name}: ({arguments}) => invoke({Quote(call.Name)}, [{arguments}]),");
        }
    }

    private static string Quote(string value) => $"'{value}'";

    private sealed class Node
    {
        public List<(string Name, Node Node)> Children { get; } = [];
        public List<(string Name, Call Call)> Calls { get; } = [];

        public Node Child(string name)
        {
            var existing = Children.FirstOrDefault(c => c.Name == name).Node;
            if (existing is not null) return existing;

            var child = new Node();
            Children.Add((name, child));
            return child;
        }
    }

    private sealed class TypeCollector
    {
        private readonly NullabilityInfoContext _nullability = new();
        private readonly Dictionary<string, Type> _types = new();

        public ICollection<string> Names => _types.Keys;

        public string Render(Type type, NullabilityInfo? info)
        {
            if (Nullable.GetUnderlyingType(type) is { } underlying)
                return $"{Render(underlying, null)} | null";

            if (!type.IsValueType && info?.ReadState == NullabilityState.Nullable)
                return $"{Render(type, null)} | null";

            if (type.IsEnum) return Register(type);

            if (type == typeof(byte[])) return Register(type);

            switch (Type.GetTypeCode(type))
            {
                case TypeCode.String:
                    return "string";
                case TypeCode.Boolean:
                    return "boolean";
                case TypeCode.Byte or TypeCode.SByte or TypeCode.Int16 or TypeCode.UInt16 or TypeCode.Int32 or TypeCode.UInt32
                    or TypeCode.Int64 or TypeCode.UInt64 or TypeCode.Single or TypeCode.Double or TypeCode.Decimal:
                    return "number";
            }

            if (ElementType(type, info) is var (element, elementInfo))
            {
                var rendered = Render(element, elementInfo);
                return rendered.Contains('|') ? $"({rendered})[]" : $"{rendered}[]";
            }

            if (Contract.IsBranded(type) || Contract.IsObject(type)) return Register(type);

            throw new NotSupportedException($"Type {type.FullName} can't cross the engine boundary.");
        }

        private string Register(Type type)
        {
            if (type == typeof(byte[]))
            {
                _types["Base64"] = type;
                return "Base64";
            }

            if (_types.TryGetValue(type.Name, out var known) && known != type)
                throw new InvalidOperationException($"Two engine types are named {type.Name}: {known.FullName} and {type.FullName}.");

            _types[type.Name] = type;
            return type.Name;
        }

        public string Declarations()
        {
            var declarations = new SortedDictionary<string, string>(StringComparer.Ordinal);
            while (_types.Keys.FirstOrDefault(n => !declarations.ContainsKey(n)) is { } name)
                declarations[name] = Declare(_types[name]);

            return Header + string.Concat(declarations.Values.Select(d => "\n" + d));
        }

        private string Declare(Type type)
        {
            if (type == typeof(byte[])) return "export type Base64 = string\n";

            if (type.IsEnum)
            {
                var members = Enum.GetNames(type).Select(n => Quote(JsonNamingPolicy.CamelCase.ConvertName(n)));
                return $"export type {type.Name} = {string.Join(" | ", members)}\n";
            }

            if (Contract.IsBranded(type))
                return $"export type {type.Name} = string & {{ readonly __brand: {Quote(type.Name)} }}\n";

            var optional = OptionalParameters(type);
            var sb = new StringBuilder($"export interface {type.Name} {{\n");
            if (Contract.IsEvent(type)) sb.AppendLine($"  type: {Quote(JsonNamingPolicy.CamelCase.ConvertName(type.Name))}");
            foreach (var property in Properties(type))
            {
                var name = JsonNamingPolicy.CamelCase.ConvertName(property.Name);
                var rendered = Render(property.PropertyType, _nullability.Create(property));
                var mark = optional.Contains(property.Name) && rendered.EndsWith(" | null") ? "?" : "";
                sb.AppendLine($"  {name}{mark}: {rendered}");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // The JSON reader passes null for a missing property, so a nullable constructor parameter with a default can be left out.
        private static HashSet<string> OptionalParameters(Type type) => type
            .GetConstructors()
            .MaxBy(c => c.GetParameters().Length)
            ?.GetParameters()
            .Where(p => p.HasDefaultValue)
            .Select(p => p.Name!)
            .ToHashSet(StringComparer.OrdinalIgnoreCase) ?? [];

        private static IEnumerable<PropertyInfo> Properties(Type type) => type
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetMethod?.IsPublic == true && p.GetIndexParameters().Length == 0)
            .DistinctBy(p => p.Name);

        private static (Type, NullabilityInfo?)? ElementType(Type type, NullabilityInfo? info)
        {
            if (type.IsArray) return (type.GetElementType()!, info?.ElementType);
            if (type == typeof(string)) return null;

            var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
                ? type
                : type.GetInterfaces().FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));

            if (enumerable is null) return null;

            var elementInfo = info?.GenericTypeArguments.Length == 1 ? info.GenericTypeArguments[0] : null;
            return (enumerable.GetGenericArguments()[0], elementInfo);
        }
    }
}
