<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PKHeX.Facade.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PKHeX.Facade\PKHeX.Facade.csproj" />
    </ItemGroup>

</Project>
