using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PKHeX.Everywhere.Engine.Generators;

[Generator]
public sealed class HandlerGenerator : IIncrementalGenerator
{
    private const string QueryAttribute = "PKHeX.Everywhere.Engine.QueryAttribute";
    private const string CommandAttribute = "PKHeX.Everywhere.Engine.CommandAttribute";
    private const string HandleInterface = "PKHeX.Everywhere.Engine.IHandle";
    private const string EventInterface = "PKHeX.Everywhere.Engine.IEngineEvent";

    private static readonly DiagnosticDescriptor NotStatic = new(
        "PKE001", "Handler must be static", "Handler '{0}' must be a static method", "Engine", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor DuplicateCall = new(
        "PKE002", "Duplicate call name", "Call '{0}' is declared more than once", "Engine", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var queries = Handlers(context, QueryAttribute);
        var commands = Handlers(context, CommandAttribute);
        var events = Events(context);
        var ns = context.CompilationProvider.Select(static (compilation, _) => Namespace(compilation.AssemblyName));

        context.RegisterSourceOutput(queries.Combine(commands).Combine(events).Combine(ns),
            static (spc, input) => Emit(spc, input.Right, input.Left.Left.Left.AddRange(input.Left.Left.Right), input.Left.Right));
    }

    private static IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> Events(IncrementalGeneratorInitializationContext context) =>
        context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
            .Where(static type => type is { TypeKind: TypeKind.Class or TypeKind.Struct, IsAbstract: false }
                                  && type.AllInterfaces.Any(i => i.ToDisplayString() == EventInterface))
            .Select(static (type, _) => type!)
            .Collect();

    private static IncrementalValueProvider<ImmutableArray<IMethodSymbol>> Handlers(IncrementalGeneratorInitializationContext context, string attribute) =>
        context.SyntaxProvider.ForAttributeWithMetadataName(
            attribute,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol).Collect();

    // Each assembly gets its own registry in its own namespace, so the Engine's internal one never clashes with it.
    private static string Namespace(string? assemblyName) => string.Join(".", (assemblyName ?? "Handlers")
        .Split('.')
        .Select(segment => new string(segment.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray()))
        .Select(segment => segment.Length == 0 || char.IsDigit(segment[0]) ? "_" + segment : segment));

    private static void Emit(SourceProductionContext context, string ns, ImmutableArray<IMethodSymbol> methods, ImmutableArray<INamedTypeSymbol> events)
    {
        var json = new JsonEmitter(context);
        var eventCases = new StringBuilder();
        foreach (var type in events.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default).OrderBy(t => t.ToDisplayString()))
            eventCases.AppendLine($"                case {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} e: {json.WriteEvent(type, "e")} return true;");

        var cases = new StringBuilder();
        var names = new List<string>();

        foreach (var method in methods.OrderBy(m => CallName(m)))
        {
            var location = method.Locations.FirstOrDefault();
            var name = CallName(method);

            if (!method.IsStatic)
            {
                context.ReportDiagnostic(Diagnostic.Create(NotStatic, location, method.Name));
                continue;
            }

            if (names.Contains(name))
            {
                context.ReportDiagnostic(Diagnostic.Create(DuplicateCall, location, name));
                continue;
            }

            names.Add(name);
            cases.Append(EmitCase(json, method, name, location));
        }

        var registry = $$"""
            // <auto-generated />
            #nullable disable
            #pragma warning disable CS1998
            using System.Text.Json;

            namespace {{ns}};

            internal static class HandlerRegistry
            {
                public static async global::System.Threading.Tasks.ValueTask<bool> TryInvoke(global::PKHeX.Everywhere.Engine.Session session, string call, JsonElement args, Utf8JsonWriter writer)
                {
                    switch (call)
                    {
            {{cases}}        }

                    return false;
                }

                public static bool TryWriteEvent(global::PKHeX.Everywhere.Engine.IEngineEvent engineEvent, Utf8JsonWriter writer)
                {
                    switch (engineEvent)
                    {
            {{eventCases}}        }

                    return false;
                }

                private static void ExpectArgs(string call, JsonElement args, int count)
                {
                    if (args.GetArrayLength() != count)
                        throw new global::PKHeX.Everywhere.Engine.EngineException(global::PKHeX.Everywhere.Engine.ErrorCodes.BadArguments, $"'{call}' takes {count} argument(s), got {args.GetArrayLength()}.");
                }

                private static T Arg<T>(string name, System.Func<T> read)
                {
                    try
                    {
                        return read();
                    }
                    catch (System.Exception e) when (e is not global::PKHeX.Everywhere.Engine.EngineException)
                    {
                        throw new global::PKHeX.Everywhere.Engine.EngineException(global::PKHeX.Everywhere.Engine.ErrorCodes.BadArguments, $"Invalid argument '{name}': {e.Message}", e);
                    }
                }
            }
            """;

        context.AddSource("HandlerRegistry.g.cs", registry);
        context.AddSource("GeneratedJson.g.cs", json.Build(ns));
    }

    private static AttributeData HandlerAttribute(IMethodSymbol method) =>
        method.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() is QueryAttribute or CommandAttribute);

    private static string CallName(IMethodSymbol method) => HandlerAttribute(method).ConstructorArguments[0].Value as string ?? "";

    private static bool IsCommand(IMethodSymbol method) => HandlerAttribute(method).AttributeClass?.ToDisplayString() == CommandAttribute;

    private static IEnumerable<string> DeclaredTopics(IMethodSymbol method) =>
        HandlerAttribute(method).ConstructorArguments[1].Values.Select(v => $"\"{v.Value}\"");

    private static bool IsHandle(ITypeSymbol type) =>
        type.AllInterfaces.Any(i => i.ToDisplayString() == HandleInterface);

    private static string EmitCase(JsonEmitter json, IMethodSymbol method, string name, Location? location)
    {
        var sb = new StringBuilder();
        var arguments = new List<string>();
        var written = new List<string>();
        var mayWriteNothing = false;
        var jsonIndex = 0;

        sb.AppendLine($"            case \"{name}\":");
        sb.AppendLine("            {");

        var jsonParameters = method.Parameters.Where(p => Injected(p.Type) is null).ToList();
        sb.AppendLine($"                ExpectArgs(call, args, {jsonParameters.Count});");

        foreach (var parameter in method.Parameters)
        {
            var type = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (Injected(parameter.Type) is { } injected)
            {
                sb.AppendLine($"                var i{arguments.Count} = {injected};");
                arguments.Add($"i{arguments.Count}");
                continue;
            }

            var read = json.Read(parameter.Type, $"args[{jsonIndex}]", location);
            sb.AppendLine($"                var a{jsonIndex} = Arg<{type}>(\"{parameter.Name}\", () => {read});");
            arguments.Add($"a{jsonIndex}");
            if (IsHandle(parameter.Type))
            {
                var nullable = parameter.Type.NullableAnnotation == NullableAnnotation.Annotated;
                mayWriteNothing |= nullable;
                written.Add(nullable ? $"a{jsonIndex}?.Topic()" : $"a{jsonIndex}.Topic()");
            }
            jsonIndex++;
        }

        var invocation = $"{method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{method.Name}({string.Join(", ", arguments)})";
        var awaited = IsTask(method.ReturnType, out var returnType);
        var returnsVoid = method.ReturnsVoid || (awaited && returnType is null);

        if (IsCommand(method))
        {
            var topics = $"new string[] {{ {string.Join(", ", written.Concat(DeclaredTopics(method)))} }}";
            if (mayWriteNothing)
                topics = $"global::System.Linq.Enumerable.ToArray(global::System.Linq.Enumerable.OfType<string>({topics}))";
            invocation = (awaited, returnsVoid) switch
            {
                (false, true) => $"session.RunCommand({topics}, () => {{ {invocation}; return true; }})",
                (false, false) => $"session.RunCommand({topics}, () => {invocation})",
                (true, true) => $"await session.RunCommandAsync({topics}, async () => {{ await {invocation}; return true; }})",
                (true, false) => $"await session.RunCommandAsync({topics}, () => {invocation})",
            };
        }
        else if (awaited)
        {
            invocation = $"await {invocation}";
        }

        if (returnsVoid)
        {
            sb.AppendLine($"                {invocation};");
            sb.AppendLine("                writer.WriteNullValue();");
        }
        else
        {
            sb.AppendLine($"                var result = {invocation};");
            sb.Append(json.Write(returnType ?? method.ReturnType, "result", "                ", location));
        }

        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        return sb.ToString();
    }

    private static bool IsTask(ITypeSymbol type, out ITypeSymbol? result)
    {
        result = null;
        if (type is not INamedTypeSymbol { ContainingNamespace: { } ns } named || ns.ToDisplayString() != "System.Threading.Tasks" || named.Name != "Task")
            return false;

        if (named.TypeArguments.Length == 1) result = named.TypeArguments[0];
        return true;
    }

    private static string? Injected(ITypeSymbol type) => type.ToDisplayString() switch
    {
        "PKHeX.Facade.Game" => "session.RequireGame()",
        "PKHeX.Everywhere.Engine.Session" => "session",
        _ => null,
    };
}
