using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PKHeX.Everywhere.Engine.Generators;

[Generator]
public sealed class HandlerGenerator : IIncrementalGenerator
{
    private const string QueryAttribute = "PKHeX.Everywhere.Engine.QueryAttribute";

    private static readonly DiagnosticDescriptor NotStatic = new(
        "PKE001", "Handler must be static", "Handler '{0}' must be a static method", "Engine", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor DuplicateCall = new(
        "PKE002", "Duplicate call name", "Call '{0}' is declared more than once", "Engine", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider.ForAttributeWithMetadataName(
            QueryAttribute,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(handlers.Collect(), static (spc, methods) => Emit(spc, methods));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        var json = new JsonEmitter(context);
        var cases = new StringBuilder();
        var names = new List<string>();

        foreach (var method in methods.OrderBy(m => CallName(m)))
        {
            var location = method.Locations.FirstOrDefault();
            var name = CallName(method);

            if (!method.IsStatic)
            {
                context.ReportDiagnostic(Diagnostic.Create(NotStatic, location, method.Name));
                continue;
            }

            if (names.Contains(name))
            {
                context.ReportDiagnostic(Diagnostic.Create(DuplicateCall, location, name));
                continue;
            }

            names.Add(name);
            cases.Append(EmitCase(json, method, name, location));
        }

        var registry = $$"""
            // <auto-generated />
            #nullable disable
            using System.Text.Json;

            namespace PKHeX.Everywhere.Engine;

            internal static class HandlerRegistry
            {
                public static bool TryInvoke(Session session, string call, JsonElement args, Utf8JsonWriter writer)
                {
                    switch (call)
                    {
            {{cases}}        }

                    return false;
                }

                private static void ExpectArgs(string call, JsonElement args, int count)
                {
                    if (args.GetArrayLength() != count)
                        throw new EngineException(ErrorCodes.BadArguments, $"'{call}' takes {count} argument(s), got {args.GetArrayLength()}.");
                }

                private static T Arg<T>(string name, System.Func<T> read)
                {
                    try
                    {
                        return read();
                    }
                    catch (System.Exception e) when (e is not EngineException)
                    {
                        throw new EngineException(ErrorCodes.BadArguments, $"Invalid argument '{name}': {e.Message}", e);
                    }
                }
            }
            """;

        context.AddSource("HandlerRegistry.g.cs", registry);
        context.AddSource("GeneratedJson.g.cs", json.Build());
    }

    private static string CallName(IMethodSymbol method) =>
        method.GetAttributes()
            .First(a => a.AttributeClass?.ToDisplayString() == QueryAttribute)
            .ConstructorArguments[0].Value as string ?? "";

    private static string EmitCase(JsonEmitter json, IMethodSymbol method, string name, Location? location)
    {
        var sb = new StringBuilder();
        var arguments = new List<string>();
        var jsonIndex = 0;

        sb.AppendLine($"            case \"{name}\":");
        sb.AppendLine("            {");

        var jsonParameters = method.Parameters.Where(p => Injected(p.Type) is null).ToList();
        sb.AppendLine($"                ExpectArgs(call, args, {jsonParameters.Count});");

        foreach (var parameter in method.Parameters)
        {
            var type = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (Injected(parameter.Type) is { } injected)
            {
                arguments.Add(injected);
                continue;
            }

            var read = json.Read(parameter.Type, $"args[{jsonIndex}]", location);
            sb.AppendLine($"                var a{jsonIndex} = Arg<{type}>(\"{parameter.Name}\", () => {read});");
            arguments.Add($"a{jsonIndex}");
            jsonIndex++;
        }

        var invocation = $"{method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{method.Name}({string.Join(", ", arguments)})";

        if (method.ReturnsVoid)
        {
            sb.AppendLine($"                {invocation};");
            sb.AppendLine("                writer.WriteNullValue();");
        }
        else
        {
            sb.AppendLine($"                var result = {invocation};");
            sb.Append(json.Write(method.ReturnType, "result", "                ", location));
        }

        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        return sb.ToString();
    }

    private static string? Injected(ITypeSymbol type) => type.ToDisplayString() switch
    {
        "PKHeX.Facade.Game" => "session.RequireGame()",
        "PKHeX.Everywhere.Engine.Session" => "session",
        _ => null,
    };
}
