using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PKHeX.Everywhere.Engine.Generators;

/// <summary>
/// Writes JSON readers and writers for handler arguments and results.
/// System.Text.Json's own generator can't see types registered by another generator, so the engine emits its own.
/// The rules here must match the TypeScript that PKHeX.Everywhere.Engine.CodeGen writes.
/// </summary>
internal sealed class JsonEmitter(SourceProductionContext context)
{
    private static readonly DiagnosticDescriptor Unsupported = new(
        "PKE003", "Type can't cross the engine boundary", "Type '{0}' can't cross the engine boundary", "Engine", DiagnosticSeverity.Error, true);

    private readonly Dictionary<string, string> _writers = new();
    private readonly Dictionary<string, string> _readers = new();
    private readonly Queue<(ITypeSymbol Type, bool Write)> _pending = new();
    private int _variable;

    public string Write(ITypeSymbol type, string value, string indent, Location? location)
    {
        var sb = new StringBuilder();
        EmitWrite(sb, type, value, indent, location);
        return sb.ToString();
    }

    public string Read(ITypeSymbol type, string element, Location? location) => ReadExpression(type, element, location);

    public string Build()
    {
        while (_pending.Count > 0)
        {
            var (type, write) = _pending.Dequeue();
            if (write) BuildWriter(type);
            else BuildReader(type);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine("namespace PKHeX.Everywhere.Engine;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedJson");
        sb.AppendLine("{");
        foreach (var method in _writers.Values.Concat(_readers.Values)) sb.AppendLine(method);
        sb.AppendLine("""
                internal static JsonElement Property(JsonElement element, string name) =>
                    element.ValueKind == JsonValueKind.Object && element.TryGetProperty(name, out var value) ? value : default;

                internal static bool IsNull(JsonElement element) =>
                    element.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined;
            """);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void EmitWrite(StringBuilder sb, ITypeSymbol type, string value, string indent, Location? location)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            var inner = Variable();
            sb.AppendLine($"{indent}if ({value} is {{ }} {inner})");
            sb.AppendLine($"{indent}{{");
            EmitWrite(sb, nullable.TypeArguments[0], inner, indent + "    ", location);
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else writer.WriteNullValue();");
            return;
        }

        if (type.IsReferenceType)
        {
            sb.AppendLine($"{indent}if ({value} is null) writer.WriteNullValue();");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            EmitNonNullWrite(sb, type, value, indent + "    ", location);
            sb.AppendLine($"{indent}}}");
            return;
        }

        EmitNonNullWrite(sb, type, value, indent, location);
    }

    private void EmitNonNullWrite(StringBuilder sb, ITypeSymbol type, string value, string indent, Location? location)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                sb.AppendLine($"{indent}writer.WriteStringValue({value});");
                return;
            case SpecialType.System_Boolean:
                sb.AppendLine($"{indent}writer.WriteBooleanValue({value});");
                return;
            case var s when IsNumber(s):
                sb.AppendLine($"{indent}writer.WriteNumberValue({value});");
                return;
        }

        if (IsBranded(type))
        {
            sb.AppendLine($"{indent}writer.WriteStringValue({value}.Value);");
            return;
        }

        if (ElementType(type) is { } element)
        {
            var item = Variable();
            sb.AppendLine($"{indent}writer.WriteStartArray();");
            sb.AppendLine($"{indent}foreach (var {item} in {value})");
            sb.AppendLine($"{indent}{{");
            EmitWrite(sb, element, item, indent + "    ", location);
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}writer.WriteEndArray();");
            return;
        }

        if (type.TypeKind == TypeKind.Enum || IsObject(type))
        {
            Enqueue(type, write: true);
            sb.AppendLine($"{indent}GeneratedJson.{MethodName("Write", type)}(writer, {value});");
            return;
        }

        Report(type, location);
    }

    private string ReadExpression(ITypeSymbol type, string element, Location? location)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            var inner = nullable.TypeArguments[0];
            return $"(GeneratedJson.IsNull({element}) ? null : ({Name(type)}){ReadExpression(inner, element, location)})";
        }

        if (type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated)
            return $"(GeneratedJson.IsNull({element}) ? null : {NonNullRead(type, element, location)})";

        return NonNullRead(type, element, location);
    }

    private string NonNullRead(ITypeSymbol type, string element, Location? location)
    {
        var primitive = type.SpecialType switch
        {
            SpecialType.System_String => "GetString",
            SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte",
            SpecialType.System_SByte => "GetSByte",
            SpecialType.System_Int16 => "GetInt16",
            SpecialType.System_UInt16 => "GetUInt16",
            SpecialType.System_Int32 => "GetInt32",
            SpecialType.System_UInt32 => "GetUInt32",
            SpecialType.System_Int64 => "GetInt64",
            SpecialType.System_UInt64 => "GetUInt64",
            SpecialType.System_Single => "GetSingle",
            SpecialType.System_Double => "GetDouble",
            SpecialType.System_Decimal => "GetDecimal",
            _ => null,
        };

        if (primitive is not null) return $"{element}.{primitive}()";

        if (IsBranded(type)) return $"new {Name(type)}({element}.GetString())";

        if (ElementType(type) is { } item)
        {
            var collect = type is IArrayTypeSymbol || type.TypeKind == TypeKind.Interface ? "ToArray"
                : type.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.List<T>" ? "ToList"
                : null;

            if (collect is not null)
            {
                var variable = Variable();
                return $"{element}.EnumerateArray().Select({variable} => {ReadExpression(item, variable, location)}).{collect}()";
            }
        }

        if (type.TypeKind == TypeKind.Enum || IsObject(type))
        {
            Enqueue(type, write: false);
            return $"GeneratedJson.{MethodName("Read", type)}({element})";
        }

        Report(type, location);
        return "default";
    }

    private void BuildWriter(ITypeSymbol type)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"    public static void {MethodName("Write", type)}(Utf8JsonWriter writer, {Name(type)} value)");
        sb.AppendLine("    {");

        if (type.TypeKind == TypeKind.Enum)
        {
            sb.AppendLine("        writer.WriteStringValue(value switch");
            sb.AppendLine("        {");
            foreach (var member in EnumMembers(type))
                sb.AppendLine($"            {Name(type)}.{member} => \"{Naming.CamelCase(member)}\",");
            sb.AppendLine("            _ => value.ToString(),");
            sb.AppendLine("        });");
        }
        else
        {
            sb.AppendLine("        writer.WriteStartObject();");
            foreach (var property in Properties(type))
            {
                sb.AppendLine($"        writer.WritePropertyName(\"{Naming.CamelCase(property.Name)}\");");
                EmitWrite(sb, property.Type, $"value.{property.Name}", "        ", property.Locations.FirstOrDefault());
            }

            sb.AppendLine("        writer.WriteEndObject();");
        }

        sb.AppendLine("    }");
        _writers[MethodName("Write", type)] = sb.ToString();
    }

    private void BuildReader(ITypeSymbol type)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"    public static {Name(type)} {MethodName("Read", type)}(JsonElement element)");
        sb.AppendLine("    {");

        if (type.TypeKind == TypeKind.Enum)
        {
            sb.AppendLine("        return element.GetString() switch");
            sb.AppendLine("        {");
            foreach (var member in EnumMembers(type))
                sb.AppendLine($"            \"{Naming.CamelCase(member)}\" => {Name(type)}.{member},");
            sb.AppendLine($"            var other => throw new System.FormatException($\"'{{other}}' is not a valid {type.Name}.\"),");
            sb.AppendLine("        };");
        }
        else
        {
            var constructor = ((INamedTypeSymbol)type).InstanceConstructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public)
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();

            var arguments = constructor?.Parameters
                .Select(p => ReadExpression(p.Type, $"GeneratedJson.Property(element, \"{Naming.CamelCase(p.Name)}\")", p.Locations.FirstOrDefault()))
                ?? [];

            sb.AppendLine($"        if (element.ValueKind != JsonValueKind.Object) throw new System.FormatException(\"Expected an object for {type.Name}.\");");
            sb.AppendLine($"        return new {Name(type)}({string.Join(", ", arguments)});");
        }

        sb.AppendLine("    }");
        _readers[MethodName("Read", type)] = sb.ToString();
    }

    private void Enqueue(ITypeSymbol type, bool write)
    {
        var name = MethodName(write ? "Write" : "Read", type);
        var built = write ? _writers : _readers;
        if (built.ContainsKey(name)) return;

        built[name] = string.Empty;
        _pending.Enqueue((type, write));
    }

    private void Report(ITypeSymbol type, Location? location) =>
        context.ReportDiagnostic(Diagnostic.Create(Unsupported, location, type.ToDisplayString()));

    private string Variable() => $"v{_variable++}";

    private static string Name(ITypeSymbol type) =>
        type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string MethodName(string prefix, ITypeSymbol type) =>
        prefix + "_" + new string(type.ToDisplayString().Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    private static bool IsNumber(SpecialType type) => type is
        SpecialType.System_Byte or SpecialType.System_SByte or
        SpecialType.System_Int16 or SpecialType.System_UInt16 or
        SpecialType.System_Int32 or SpecialType.System_UInt32 or
        SpecialType.System_Int64 or SpecialType.System_UInt64 or
        SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_Decimal;

    private static bool IsBranded(ITypeSymbol type) =>
        type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "PKHeX.Everywhere.Engine.BrandedAttribute");

    private static bool IsObject(ITypeSymbol type) =>
        type is INamedTypeSymbol { TypeKind: TypeKind.Class or TypeKind.Struct, IsGenericType: false } &&
        type.SpecialType == SpecialType.None &&
        type.ContainingNamespace.ToDisplayString().StartsWith("PKHeX.Everywhere.Engine");

    private static ITypeSymbol? ElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array) return array.ElementType;
        if (type.SpecialType == SpecialType.System_String) return null;

        var candidates = type is INamedTypeSymbol named ? type.AllInterfaces.Prepend(named) : type.AllInterfaces;
        return candidates
            .FirstOrDefault(i => i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
            ?.TypeArguments[0];
    }

    private static IEnumerable<string> EnumMembers(ITypeSymbol type) =>
        type.GetMembers().OfType<IFieldSymbol>().Where(f => f.IsConst).Select(f => f.Name);

    private static IEnumerable<IPropertySymbol> Properties(ITypeSymbol type)
    {
        var seen = new HashSet<string>();
        for (var current = type; current is { SpecialType: not SpecialType.System_Object }; current = current.BaseType)
        {
            foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (property is { IsStatic: false, IsIndexer: false, DeclaredAccessibility: Accessibility.Public, GetMethod.DeclaredAccessibility: Accessibility.Public }
                    && seen.Add(property.Name))
                    yield return property;
            }
        }
    }
}

internal static class Naming
{
    // Mirrors System.Text.Json's JsonNamingPolicy.CamelCase, which CodeGen uses for the TypeScript side.
    public static string CamelCase(string name)
    {
        if (string.IsNullOrEmpty(name) || !char.IsUpper(name[0])) return name;

        var chars = name.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
        {
            if (i == 1 && !char.IsUpper(chars[i])) break;

            var hasNext = i + 1 < chars.Length;
            if (i > 0 && hasNext && !char.IsUpper(chars[i + 1]))
            {
                if (char.IsSeparator(chars[i + 1])) chars[i] = char.ToLowerInvariant(chars[i]);
                break;
            }

            chars[i] = char.ToLowerInvariant(chars[i]);
        }

        return new string(chars);
    }
}
