name: Release plug-ins

on:
  # for now, no automated plug-in releases
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'src/PKHeX.Web.Plugins/**'
  #     - 'src/PKHeX.Web.Plugins*/**'
      
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Update submodules to the latest commit
        run: |
          git submodule update --remote --recursive
          
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          chmod +x ./build-plugins.sh
          chmod +x ./gen-pkhexwebplugins.sh
          
          ./build-plugins.sh
          ./gen-pkhexwebplugins.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-plugin-assets
          path: ./plugins

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_publish

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: plugins
      - name: List assets
        run: ls -R plugins
        
      - name: Checkout plugins-source-assets repository
        uses: actions/checkout@v4
        with:
          repository: pkhex-web/plugins-source-assets
          ref: main
          path: plugins-source-assets
          token: ${{ secrets.GIT_HUB_PKHEX_WEB_TOKEN }}

      - name: Copy artifacts to assets repository
        run: |
          cp -R plugins/artifact-plugin-assets/* plugins-source-assets/

      - name: Commit and push new artifacts
        run: |
          cd plugins-source-assets
          touch .nojekyll
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add --all
          git commit -m "update plugins"
          git push origin
          cd ..
